/**
 * Company: EonHive Inc.
 * Title: Create Proof Template
 * Purpose: Generate the repo-only proof files for `urk create-proof <name>`.
 * Author: Stan Nesi
 * Created: 2026-05-03
 * Updated: 2026-05-03
 * Notes: Vibe coded with Codex.
 */

import { toPascalCase } from '../utils/names.js';

export type CreateProofTemplateOptions = {
  name: string;
};

export type CreateProofTemplateResult = Record<string, string>;

function createTitleFromName(name: string): string {
  const baseTitle = toPascalCase(name).replace(/([a-z0-9])([A-Z])/g, '$1 $2');

  return /\bproof$/i.test(baseTitle) ? baseTitle : `${baseTitle} Proof`;
}

/**
 * Build the file map for a repo-only examples proof route.
 * The proof stays DOM-first and shows one explicit kernel, one controller, and one small adapter stack.
 */
export function createProofTemplate(
  options: CreateProofTemplateOptions,
): CreateProofTemplateResult {
  const title = createTitleFromName(options.name);

  return {
    'README.md': `# ${title}

Route: \`/${options.name}/\`

This repo-only proof demonstrates one standalone URK kernel, one small DOM adapter stack, one controller, and an explicit runtime phase transition from \`loading\` to \`ready\`.

## Uses

- \`@urk/core\`
- \`@urk/adapters/dom\`

## Files

- \`index.html\` - proof shell
- \`styles.css\` - proof styling
- \`main.ts\` - kernel setup, controller flow, and DOM projection
`,
    'index.html': `<!--
  Company: EonHive Inc.
  Title: ${title}
  Purpose: Mount the repo-only URK proof generated by @urk/cli.
  Author: Stan Nesi
  Created: 2026-05-03
  Updated: 2026-05-03
  Notes: Vibe coded with Codex.
-->
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${title}</title>
    <link rel="stylesheet" href="./styles.css" />
  </head>
  <body>
    <div id="app">
      <main class="proof-shell">
        <section class="proof-panel">
          <span class="proof-eyebrow">Repo-only proof</span>
          <h1>${title}</h1>
          <p>
            This generated proof keeps the runtime easy to read: one kernel, one controller,
            three DOM adapters, explicit phases, and one overlay host.
          </p>

          <div class="metric-grid">
            <article class="metric-card">
              <span>Runtime phase</span>
              <strong data-role="phase-value">boot</strong>
            </article>
            <article class="metric-card">
              <span>Phase reason</span>
              <strong data-role="reason-value">kernel:init</strong>
            </article>
            <article class="metric-card">
              <span>Loading stage</span>
              <strong data-role="stage-value">Waiting to start</strong>
            </article>
            <article class="metric-card">
              <span>Loading progress</span>
              <strong data-role="progress-value">0%</strong>
            </article>
          </div>
        </section>

        <section class="proof-stage">
          <article class="stage-card">
            <span class="stage-meta">Controller-managed runtime</span>
            <h2 data-role="message-value">Waiting to boot</h2>
            <p data-role="detail-value">
              The proof controller will stage loading, update the shell, and move the runtime into the ready phase.
            </p>
          </article>
          <div class="ui-host" data-role="ui-host"></div>
        </section>
      </main>
    </div>

    <script type="module" src="./main.ts"></script>
  </body>
</html>
`,
    'styles.css': `/*
 * Company: EonHive Inc.
 * Title: ${title} Styles
 * Purpose: Keep the generated proof styling separate from proof logic.
 * Author: Stan Nesi
 * Created: 2026-05-03
 * Updated: 2026-05-03
 * Notes: Vibe coded with Codex.
 */

:root {
  color-scheme: light;
  font-family: "Avenir Next", "Segoe UI", sans-serif;
  background:
    radial-gradient(circle at top left, rgba(59, 130, 246, 0.14), transparent 34%),
    radial-gradient(circle at bottom right, rgba(34, 197, 94, 0.1), transparent 28%),
    #f4f7fb;
  color: #102033;
}

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  min-height: 100vh;
}

#app {
  min-height: 100vh;
  padding: 24px;
}

.proof-shell {
  width: min(1100px, 100%);
  margin: 0 auto;
  display: grid;
  gap: 18px;
  grid-template-columns: minmax(0, 340px) minmax(0, 1fr);
}

.proof-panel,
.proof-stage {
  border-radius: 28px;
  border: 1px solid rgba(148, 163, 184, 0.18);
  background: rgba(255, 255, 255, 0.84);
  box-shadow: 0 18px 40px rgba(15, 23, 42, 0.08);
  backdrop-filter: blur(14px);
}

.proof-panel {
  padding: 22px;
  display: grid;
  gap: 18px;
  align-content: start;
}

.proof-stage {
  position: relative;
  min-height: 480px;
  overflow: hidden;
  background:
    radial-gradient(circle at top, rgba(14, 165, 233, 0.14), transparent 40%),
    linear-gradient(180deg, rgba(15, 23, 42, 0.03), rgba(15, 23, 42, 0.08)),
    #f8fafc;
}

.proof-eyebrow,
.stage-meta {
  display: inline-flex;
  width: max-content;
  padding: 8px 12px;
  border-radius: 999px;
  background: rgba(226, 232, 240, 0.78);
  color: #102033;
  font-size: 0.78rem;
  letter-spacing: 0.1em;
  text-transform: uppercase;
}

.proof-panel h1,
.stage-card h2 {
  margin: 0;
  font-family: "Trebuchet MS", "Avenir Next", sans-serif;
  letter-spacing: -0.04em;
  color: #0f172a;
}

.proof-panel h1 {
  font-size: clamp(2rem, 5vw, 3.4rem);
  line-height: 0.96;
}

.proof-panel p,
.stage-card p {
  margin: 0;
  color: #475569;
  line-height: 1.65;
}

.metric-grid {
  display: grid;
  gap: 12px;
}

.metric-card,
.stage-card {
  border-radius: 20px;
  background: #f8fafc;
  border: 1px solid rgba(148, 163, 184, 0.16);
}

.metric-card {
  padding: 14px 16px;
}

.metric-card span {
  display: block;
  margin-bottom: 6px;
  font-size: 0.78rem;
  letter-spacing: 0.09em;
  text-transform: uppercase;
  color: #64748b;
}

.metric-card strong {
  display: block;
  font-size: 1rem;
  line-height: 1.4;
}

.stage-card {
  width: min(520px, 100%);
  padding: 22px;
  display: grid;
  gap: 14px;
  margin: 24px;
}

.stage-card h2 {
  font-size: clamp(1.8rem, 4vw, 2.9rem);
}

.ui-host {
  position: absolute;
  inset: 0;
}

@media (max-width: 860px) {
  #app {
    padding: 18px;
  }

  .proof-shell {
    grid-template-columns: 1fr;
  }

  .proof-stage {
    min-height: 400px;
  }

  .stage-card {
    margin: 18px;
  }
}
`,
    'main.ts': `/**
 * Company: EonHive Inc.
 * Title: ${title} Runtime
 * Purpose: Prove a small standalone URK flow through one kernel, one controller, and DOM adapters.
 * Author: Stan Nesi
 * Created: 2026-05-03
 * Updated: 2026-05-03
 * Notes: Vibe coded with Codex.
 */

import {
  createKernel,
  type ControllerRegistration,
  type FrameInfo,
  type RuntimeSnapshot,
} from '@urk/core';
import {
  createInputAdapter,
  createLoadingAdapter,
  createUiWidgetsAdapter,
  type InputAdapterApi,
  type LoadingAdapterApi,
  type LoadingSnapshot,
  type UiWidgetsAdapterApi,
} from '@urk/adapters/dom';

type ProofElements = {
  phaseValue: HTMLElement;
  reasonValue: HTMLElement;
  stageValue: HTMLElement;
  progressValue: HTMLElement;
  messageValue: HTMLElement;
  detailValue: HTMLElement;
  uiHost: HTMLElement;
};

const STAGES = [
  { id: 'bootstrap-proof', label: 'Bootstrap proof' },
  { id: 'bind-runtime', label: 'Bind runtime shell' },
  { id: 'activate-ready', label: 'Activate ready phase' },
] as const;

const BOOTSTRAP_DURATION_MS = 700;
const BIND_DURATION_MS = 900;
const READY_DURATION_MS = 800;

function assertElement<T extends Element>(value: T | null, label: string): T {
  if (!value) {
    throw new Error(\`Missing DOM element: \${label}\`);
  }

  return value;
}

function createLayout(): ProofElements {
  const app = assertElement(document.querySelector<HTMLDivElement>('#app'), '#app');

  return {
    phaseValue: assertElement(app.querySelector('[data-role="phase-value"]'), 'phase value'),
    reasonValue: assertElement(app.querySelector('[data-role="reason-value"]'), 'reason value'),
    stageValue: assertElement(app.querySelector('[data-role="stage-value"]'), 'stage value'),
    progressValue: assertElement(app.querySelector('[data-role="progress-value"]'), 'progress value'),
    messageValue: assertElement(app.querySelector('[data-role="message-value"]'), 'message value'),
    detailValue: assertElement(app.querySelector('[data-role="detail-value"]'), 'detail value'),
    uiHost: assertElement(app.querySelector('[data-role="ui-host"]'), 'ui host'),
  };
}

function renderPhase(snapshot: RuntimeSnapshot, elements: ProofElements): void {
  elements.phaseValue.textContent = snapshot.phase;
  elements.reasonValue.textContent = snapshot.reason ?? 'No reason provided';
}

function renderLoading(snapshot: LoadingSnapshot, elements: ProofElements): void {
  elements.stageValue.textContent = snapshot.stageLabel ?? 'Waiting to start';
  elements.progressValue.textContent = \`\${Math.round(snapshot.progress * 100)}%\`;
}

function renderMessage(message: string, detail: string, elements: ProofElements): void {
  elements.messageValue.textContent = message;
  elements.detailValue.textContent = detail;
}

function createProofController(elements: ProofElements): ControllerRegistration {
  let elapsedMs = 0;
  let completed = false;
  let unbindHelpKey: (() => void) | null = null;

  return {
    id: '${options.name}-controller',
    init(ctx) {
      renderPhase(ctx.state.getSnapshot(), elements);
      renderMessage(
        'Booting proof kernel',
        'The proof kernel is creating runtime context, registering adapters, and preparing controller lifecycle.',
        elements,
      );
    },
    start(ctx) {
      const loading = ctx.adapters.require<LoadingAdapterApi>('loading');
      const input = ctx.adapters.require<InputAdapterApi>('input');
      const widgets = ctx.adapters.require<UiWidgetsAdapterApi>('ui-widgets');

      loading.begin([...STAGES], 'Booting repo-only proof');
      renderLoading(loading.getSnapshot(), elements);
      widgets.setStatus('Phase: loading');
      widgets.showCallout({
        title: 'Proof ready to explain itself',
        body: 'Press H to reopen this help callout while the proof is running.',
        tone: 'active',
      });

      unbindHelpKey = input.bindKey({
        code: 'KeyH',
        handler() {
          widgets.showCallout({
            title: '${title}',
            body: 'This proof stays DOM-first: one kernel, one controller, and one explicit overlay host.',
            tone: 'active',
          });
        },
      });
    },
    update(frame: FrameInfo, ctx) {
      if (completed) {
        return;
      }

      const loading = ctx.adapters.require<LoadingAdapterApi>('loading');
      const widgets = ctx.adapters.require<UiWidgetsAdapterApi>('ui-widgets');
      const deltaMs = frame.deltaMs === 0 ? 16 : frame.deltaMs;

      elapsedMs += deltaMs;

      if (elapsedMs < BOOTSTRAP_DURATION_MS) {
        loading.setStage(
          'bootstrap-proof',
          elapsedMs / BOOTSTRAP_DURATION_MS,
          'Creating the proof shell and explicit runtime context',
        );
        renderLoading(loading.getSnapshot(), elements);
        renderMessage(
          'Bootstrapping the proof',
          'The kernel exists and the controller is driving staged progress through the loading adapter.',
          elements,
        );
        return;
      }

      if (elapsedMs < BOOTSTRAP_DURATION_MS + BIND_DURATION_MS) {
        loading.setStage(
          'bind-runtime',
          (elapsedMs - BOOTSTRAP_DURATION_MS) / BIND_DURATION_MS,
          'Binding shell updates and overlay capabilities',
        );
        renderLoading(loading.getSnapshot(), elements);
        renderMessage(
          'Binding runtime capabilities',
          'Adapters expose DOM capabilities and the controller keeps the proof shell in sync.',
          elements,
        );
        return;
      }

      if (elapsedMs < BOOTSTRAP_DURATION_MS + BIND_DURATION_MS + READY_DURATION_MS) {
        loading.setStage(
          'activate-ready',
          (elapsedMs - BOOTSTRAP_DURATION_MS - BIND_DURATION_MS) / READY_DURATION_MS,
          'Moving the runtime from loading to ready',
        );
        renderLoading(loading.getSnapshot(), elements);
        renderMessage(
          'Activating ready runtime',
          'The controller is about to complete loading and set the runtime phase to ready.',
          elements,
        );
        return;
      }

      loading.complete('Proof ready');
      renderLoading(loading.getSnapshot(), elements);
      renderMessage(
        'Proof ready',
        'The runtime reached ready. The proof has shown kernel boot, adapter registration, controller lifecycle, and DOM output.',
        elements,
      );
      widgets.setStatus('Phase: ready');
      ctx.state.setPhase('ready', '${options.name}:ready');
      completed = true;
    },
    onStateChange(next, _previous, ctx) {
      const widgets = ctx.adapters.get<UiWidgetsAdapterApi>('ui-widgets');

      renderPhase(next, elements);
      widgets?.setStatus(\`Phase: \${next.phase}\`);

      if (next.phase === 'error') {
        widgets?.showCallout({
          title: 'Runtime error',
          body: next.reason ?? 'An unknown runtime error occurred.',
          tone: 'selected',
        });
      }
    },
    dispose(ctx) {
      const widgets = ctx.adapters.get<UiWidgetsAdapterApi>('ui-widgets');

      unbindHelpKey?.();
      unbindHelpKey = null;
      widgets?.hideCallout();
      renderMessage(
        'Proof disposed',
        'The controller released its input binding and the proof shut down cleanly.',
        elements,
      );
    },
  };
}

const elements = createLayout();

const kernel = createKernel({
  services: {
    'ui:host': elements.uiHost,
  },
  adapters: [
    createLoadingAdapter(),
    createInputAdapter(),
    createUiWidgetsAdapter(),
  ],
  controllers: [createProofController(elements)],
});

renderPhase(kernel.getState(), elements);

window.addEventListener(
  'beforeunload',
  () => {
    void kernel.shutdown('window:unload');
  },
  { once: true },
);

async function bootProof(): Promise<void> {
  try {
    await kernel.boot();
  } catch (runtimeError) {
    renderMessage(
      'Proof boot failed',
      runtimeError instanceof Error ? runtimeError.message : 'Unexpected runtime failure',
      elements,
    );
    throw runtimeError;
  }
}

void bootProof();
`,
  };
}
